name: Cloud Integration Tests

on:
  workflow_dispatch:
    inputs:
      CLOUD_MARQO_URL:
        description: 'MARQO_URL for cloud integration tests'
        required: true
      CLOUD_MARQO_API_KEY:
        description: 'MARQO_API_KEY for cloud integration tests'
        required: true
      job_to_run :
        description: 'Job to run'
        required: true
        default: 'cleanup_indexes'
  pull_request:
    branches:
      - mainline
      - 'releases/*'
  # allows other workflows to reuse these unit tests:
  workflow_call:

permissions:
  contents: read

jobs:
  integration_tests:
    name: Cloud Integration Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'integration_tests' || github.event_name == 'pull_request' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"

      - name: Install tox
        run: pip install tox

      - name: Run tox
        env:
          MARQO_URL: ${{ secrets.CLOUD_MARQO_URL }}
          MARQO_CLOUD_URL: ${{ secrets.CLOUD_MARQO_URL }}
          MARQO_API_KEY: ${{ secrets.CLOUD_MARQO_API_KEY }}
        run: tox -e cloud_tests -- create-indexes=True use-unique-identifier=True delete-indexes=True

  cleanup_indexes:
    name: Cleanup cloud indexes
    runs-on : ubuntu-latest
    if: ${{ github.event.inputs.job_to_run == 'cleanup_indexes' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run cleanup_indexes.py
        env:
          MARQO_URL: ${{ secrets.CLOUD_MARQO_URL }}
          MARQO_CLOUD_URL: ${{ secrets.CLOUD_MARQO_URL }}
          MARQO_API_KEY: ${{ secrets.CLOUD_MARQO_API_KEY }}
        run: python tests/cloud_tests/cleanup_indexes.py
